clonedirectory = "/var/lib/spiegel/"
interval = 10

[log]
level = "DEBUG"
file = "" # Default in stderr

[[RepoList]]
URL = "https://github.com/torvalds/linux/"
name = "linux"

[[RepoList]]
URL = "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
name = "linuxtwo"